apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: luc8k9m8s-nodejs 
  janus-idp.io/tekton: luc8k9m8s-nodejs
  backstage.io/kubernetes-id: luc8k9m8s-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: luc8k9m8s-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  