apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: luc8k9m8s-nodejs
  janus-idp.io/tekton: luc8k9m8s-nodejs
  backstage.io/kubernetes-id: luc8k9m8s-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: luc8k9m8s-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
