apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: luc8k9m8s-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: luc8k9m8s-nodejs 
  name: luc8k9m8s-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: luc8k9m8s-nodejs 
